ALTER TABLE profesionales
MODIFY COLUMN apellido VARCHAR(150) NULL,
MODIFY COLUMN profesion VARCHAR(100) NULL,
MODIFY COLUMN email VARCHAR(255) NULL,
MODIFY COLUMN telefono VARCHAR(20) NULL,
MODIFY COLUMN direccion VARCHAR(255) NULL;