ALTER TABLE profesionales MODIFY COLUMN profesion ENUM(
    'MAYORISTA',
    'FARMACIA',
    'COSMETOLOGIA',
    'COSMIATRIA',
    'DERMOCOSMIATRIA',
    'ESTETICISTA',
    'MASAJISTA',
    'CONSUMIDOR_FINAL'
) NOT NULL;